apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2025-06-19T10:14:35Z"
    labels:
      app: mysql
    name: mysql
    namespace: cristian-wordpress-app
    resourceVersion: "1355656"
    uid: d6130e2f-b113-4658-8690-b8e01e43affe
  spec:
    clusterIP: 172.30.40.253
    clusterIPs:
    - 172.30.40.253
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
    selector:
      app: mysql
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2025-06-19T10:14:35Z"
    labels:
      app: wordpress
    name: wordpress-svc
    namespace: cristian-wordpress-app
    resourceVersion: "1355663"
    uid: 519d9fef-19b3-41a3-9f52-f8f9b300b3c6
  spec:
    clusterIP: 172.30.13.246
    clusterIPs:
    - 172.30.13.246
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: wordpress
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2025-06-19T10:15:30Z"
    labels:
      app: wordpress
    name: wordpress-svc-2
    namespace: cristian-wordpress-app
    resourceVersion: "1356623"
    uid: 656c965b-a543-4b76-b5f5-9b7497b5a250
  spec:
    clusterIP: 172.30.118.149
    clusterIPs:
    - 172.30.118.149
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - nodePort: 31895
      port: 80
      protocol: TCP
      targetPort: 80
    selector:
      app: wordpress
    sessionAffinity: None
    type: NodePort
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
