apiVersion: v1
imagePullSecrets:
- name: wordpress-sa-dockercfg-m7mvt
kind: ServiceAccount
metadata:
  annotations:
    openshift.io/internal-registry-pull-secret-ref: wordpress-sa-dockercfg-m7mvt
  name: wordpress-sa
  namespace: cristian-wordpress-app
secrets:
- name: wordpress-sa-dockercfg-m7mvt
